"""add 'change' column to Rank

Revision ID: 81100731d54d
Revises: b5f60837636a
Create Date: 2017-07-09 11:33:14.535392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81100731d54d'
down_revision = 'b5f60837636a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank', sa.Column('change', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank', 'change')
    # ### end Alembic commands ###
