"""add indexes

Revision ID: b5f60837636a
Revises: b6e097dd31aa
Create Date: 2017-07-09 11:15:55.578212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f60837636a'
down_revision = 'b6e097dd31aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_name'), 'book', ['name'], unique=True)
    op.create_index(op.f('ix_book_track'), 'book', ['track'], unique=False)
    op.create_index(op.f('ix_rank_book_category_timestamp'), 'rank', ['book_id', 'category_id', 'timestamp'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_track'), table_name='book')
    op.drop_index(op.f('ix_book_name'), table_name='book')
    op.drop_index(op.f('ix_rank_book_category_timestamp'), table_name='rank')
    # ### end Alembic commands ###
